CREATE TABLESPACE PRM_SYSTEM_D
  DATAFILE '/opt/oracle/oradata/FREE/FREEPDB1/prm_system_d01.dbf'
  SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

ALTER USER prm_system_copy QUOTA UNLIMITED ON PRM_SYSTEM_D;
EXIT