-- יצירת 10 טבלאות הקליטה של ממשק החינוך, בדיוק לפי LD_Chinuch.ctl:
-- כל שדות הנתונים VARCHAR2(100) (כמו במערכת הקיימת), ובנוסף בכל טבלה
-- LOAD_DATE (ה-CTL ממלא SYSDATE) ו-SEQ (ה-CTL ממלא sequence(1,1)).
--
-- הרצה (אחרי שהקונטיינר עלה):
--   docker exec -i oracle-chinuch sqlplus -s chinuch/chinuch123@localhost/FREEPDB1 @/opt/chinuch/create_tables.sql
--
-- DROP TABLE IF EXISTS נתמך מ-Oracle 23 - מאפשר הרצה חוזרת נקייה.

DROP TABLE IF EXISTS LD_CHINUCH_9015_TITLE;
CREATE TABLE LD_CHINUCH_9015_TITLE (
  MISPAR_TNUA       VARCHAR2(100),
  MISPAR_ZEHUT      VARCHAR2(100),
  ZIHUY_NOSAF       VARCHAR2(100),
  CODE_SUG_MIMSHAK  VARCHAR2(100),
  LOAD_DATE         DATE,
  SEQ               NUMBER
);

DROP TABLE IF EXISTS LD_CHINUCH_9022_PRATIM_ISHIYM;
CREATE TABLE LD_CHINUCH_9022_PRATIM_ISHIYM (
  MISPAR_TNUA        VARCHAR2(100),
  KOD_PEULA          VARCHAR2(100),
  SUG_ZIHUY          VARCHAR2(100),
  MISPAR_ZEHUT       VARCHAR2(100),
  ZIHUY_NOSAF        VARCHAR2(100),
  SHEM_MISHPACHA     VARCHAR2(100),
  SHEM_PRATI         VARCHAR2(100),
  MISRAD_AGAF        VARCHAR2(100),
  TAA_LEDA           VARCHAR2(100),
  MIN                VARCHAR2(100),
  MATSAV_MISHPACHTI  VARCHAR2(100),
  TAA_ALIYA          VARCHAR2(100),
  HORE_SHAKUL        VARCHAR2(100),
  DOAR_ELEKTRONY     VARCHAR2(100),
  LOAD_DATE          DATE,
  SEQ                NUMBER
);

DROP TABLE IF EXISTS LD_CHINUCH_9023_OVED_PORESH;
CREATE TABLE LD_CHINUCH_9023_OVED_PORESH (
  MISPAR_TNUA               VARCHAR2(100),
  KOD_PEULA                 VARCHAR2(100),
  MISPAR_ZEHUT              VARCHAR2(100),
  ZIHUY_NOSAF               VARCHAR2(100),
  MACHOZ                    VARCHAR2(100),
  GANENET                   VARCHAR2(100),
  MEGAMA                    VARCHAR2(100),
  DARGA                     VARCHAR2(100),
  TAARICH_DARGA             VARCHAR2(100),
  KIDUM_DARGA               VARCHAR2(100),
  DERUG_OFEK                VARCHAR2(100),
  DARGAT_OFEK               VARCHAR2(100),
  OFEK_CHADASH              VARCHAR2(100),
  TAARICH_HIZTARFUT_LEOFEK  VARCHAR2(100),
  HEKEF_MISRA_BOFEK         VARCHAR2(100),
  TAARICH_KNISA             VARCHAR2(100),
  OZ_LETMURA                VARCHAR2(100),
  TAARICH_HIZTARFUT_LEOZ    VARCHAR2(100),
  GMULEY_HISHTALMUT_OZ      VARCHAR2(100),
  HEKEF_MISRA_OZ            VARCHAR2(100),
  VETEK_HORAHA              VARCHAR2(100),
  VETEK_MISRAD              VARCHAR2(100),
  VETEK_TZAHAL              VARCHAR2(100),
  GMULEY_HISHTALMUT         VARCHAR2(100),
  KEFEL_TOAR                VARCHAR2(100),
  GMUL_BANAIM               VARCHAR2(100),
  LOAD_DATE                 DATE,
  SEQ                       NUMBER
);

DROP TABLE IF EXISTS LD_CHINUCH_9024_KTOVET_OVED;
CREATE TABLE LD_CHINUCH_9024_KTOVET_OVED (
  MISPAR_TNUA      VARCHAR2(100),
  KOD_PEULA        VARCHAR2(100),
  MISPAR_ZEHUT     VARCHAR2(100),
  ZIHUY_NOSAF      VARCHAR2(100),
  SEMEL_YISHUV     VARCHAR2(100),
  SHEM_RECHOV      VARCHAR2(100),
  MIKUD            VARCHAR2(100),
  KIDOMET          VARCHAR2(100),
  TELEPHONE        VARCHAR2(100),
  KIDOMET_NOSEFET  VARCHAR2(100),
  TELEPHONE_NOSAF  VARCHAR2(100),
  TAARICH_KTOVET   VARCHAR2(100),
  LOAD_DATE        DATE,
  SEQ              NUMBER
);

DROP TABLE IF EXISTS LD_CHINUCH_9025_BNEY_MISHPACHA;
CREATE TABLE LD_CHINUCH_9025_BNEY_MISHPACHA (
  MISPAR_TNUA   VARCHAR2(100),
  KOD_PEULA     VARCHAR2(100),
  MISPAR_ZEHUT  VARCHAR2(100),
  ZIHUY_NOSAF   VARCHAR2(100),
  KIRVA         VARCHAR2(100),
  SHEM_PRATI    VARCHAR2(100),
  TAARICH_LEDA  VARCHAR2(100),
  ZEHUT         VARCHAR2(100),
  METZAYEN      VARCHAR2(100),
  MEKOM_AVODA   VARCHAR2(100),
  LOAD_DATE     DATE,
  SEQ           NUMBER
);

DROP TABLE IF EXISTS LD_CHINUCH_9030_AVODA_KODMIM;
CREATE TABLE LD_CHINUCH_9030_AVODA_KODMIM (
  MISPAR_TNUA      VARCHAR2(100),
  KOD_PEULA        VARCHAR2(100),
  MISPAR_ZEHUT     VARCHAR2(100),
  ZIHUY_NOSAF      VARCHAR2(100),
  TAARICH_ME       VARCHAR2(100),
  TAARICH_AD       VARCHAR2(100),
  SUG_MEKOM_AVODA  VARCHAR2(100),
  SHEM_MAAVID      VARCHAR2(100),
  ZCHUYOT_PENSIA   VARCHAR2(100),
  KEREN_PENSIA     VARCHAR2(100),
  TAARICH_HESKEM   VARCHAR2(100),
  LOAD_DATE        DATE,
  SEQ              NUMBER
);

DROP TABLE IF EXISTS LD_CHINUCH_9031_PORSHIM;
CREATE TABLE LD_CHINUCH_9031_PORSHIM (
  MISPAR_TNUA                  VARCHAR2(100),
  KOD_PEULA                    VARCHAR2(100),
  MISPAR_ZEHUT                 VARCHAR2(100),
  ZIHUY_NOSAF                  VARCHAR2(100),
  TAARICH_PRISHA               VARCHAR2(100),
  SACH_CHODASHIM               VARCHAR2(100),
  ACHUZ_KITZBA                 VARCHAR2(100),
  TAT_SEIF_PRISHA              VARCHAR2(100),
  SEIF_PRISHA                  VARCHAR2(100),
  ACHUZ_NECHUT                 VARCHAR2(100),
  MUGBAL_LETKUFA               VARCHAR2(100),
  ORECH_SHERUT                 VARCHAR2(100),
  LEFI_NECHUT                  VARCHAR2(100),
  MISRAD                       VARCHAR2(100),
  TIKUN_27                     VARCHAR2(100),
  TIKUN_31                     VARCHAR2(100),
  HAARACHA                     VARCHAR2(100),
  CHELKIUT                     VARCHAR2(100),
  IND_PRISHA_LO_BESOF_CHODESH  VARCHAR2(100),
  ME_TAARICH_MEVUKASH          VARCHAR2(100),
  AD_TAARICH_MEVUKASH          VARCHAR2(100),
  TAARICH_CHATIMAT_TOFES       VARCHAR2(100),
  LOAD_DATE                    DATE,
  SEQ                          NUMBER
);

DROP TABLE IF EXISTS LD_CHINUCH_9032_HAGDALOT;
CREATE TABLE LD_CHINUCH_9032_HAGDALOT (
  MISPAR_TNUA        VARCHAR2(100),
  KOD_PEULA          VARCHAR2(100),
  MISPAR_ZEHUT       VARCHAR2(100),
  ZIHUY_NOSAF        VARCHAR2(100),
  TAARICH_HAGDALA    VARCHAR2(100),
  SHERUT_MUGDAL      VARCHAR2(100),
  CODE_HACHLATA      VARCHAR2(100),
  BE_KFIFUT_LE_SEIF  VARCHAR2(100),
  LEFY_SEIF_1        VARCHAR2(100),
  SHIUR_HAGDALA_1    VARCHAR2(100),
  LEFY_SEIF_2        VARCHAR2(100),
  SHIUR_HAGDALA_2    VARCHAR2(100),
  LEFY_SEIF_3        VARCHAR2(100),
  SHIUR_HAGDALA_3    VARCHAR2(100),
  LEFY_SEIF_4        VARCHAR2(100),
  SHIUR_HAGDALA_4    VARCHAR2(100),
  LEFY_SEIF_5        VARCHAR2(100),
  SHIUR_HAGDALA_5    VARCHAR2(100),
  LEFY_SEIF_6        VARCHAR2(100),
  SHIUR_HAGDALA_6    VARCHAR2(100),
  TAARICH_TCHULA     VARCHAR2(100),
  TAARICH_ISHUR      VARCHAR2(100),
  LOAD_DATE          DATE,
  SEQ                NUMBER
);

DROP TABLE IF EXISTS LD_CHINUCH_9034_SHERUT_TSVAII;
CREATE TABLE LD_CHINUCH_9034_SHERUT_TSVAII (
  MISPAR_TNUA      VARCHAR2(100),
  KOD_PEULA        VARCHAR2(100),
  MISPAR_ZEHUT     VARCHAR2(100),
  ZIHUY_NOSAF      VARCHAR2(100),
  MISPAR_ISHI      VARCHAR2(100),
  TAARICH_ME       VARCHAR2(100),
  KOD_SHERUT       VARCHAR2(100),
  TAARICH_AD       VARCHAR2(100),
  TAARICH_ZCHUYOT  VARCHAR2(100),
  LOAD_DATE        DATE,
  SEQ              NUMBER
);

DROP TABLE IF EXISTS LD_CHINUCH_9050_TKUFOT_RETSIF;
CREATE TABLE LD_CHINUCH_9050_TKUFOT_RETSIF (
  MISPAR_TNUA           VARCHAR2(100),
  KOD_PEULA             VARCHAR2(100),
  SEMEL_MISRAD          VARCHAR2(100),
  MISPAR_ZEHUT          VARCHAR2(100),
  ZIHUY_NOSAF           VARCHAR2(100),
  SUG_TKUFA             VARCHAR2(100),
  TAARICH_ME            VARCHAR2(100),
  TAARICH_AD            VARCHAR2(100),
  ORECH_SHERUT          VARCHAR2(100),
  SUG_ZECHUYOT_LEGIMLA  VARCHAR2(100),
  HEKEF_MISRA           VARCHAR2(100),
  LOAD_DATE             DATE,
  SEQ                   NUMBER
);

SELECT table_name FROM user_tables ORDER BY table_name;
EXIT
